# Generated by Django 3.1.3 on 2020-11-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_habit_record"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="goal",
            new_name="number",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="habit",
            name="noun_singular",
            field=models.CharField(default="widget", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="habit",
            name="created_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(
                fields=("habit", "date"), name="unique_record"
            ),
        ),
    ]
