# Generated by Django 3.1.3 on 2020-11-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201108_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
